apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-01-23T12:00:53Z"
  generation: 1
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: c1595d31-17e8-4a05-9002-d7399f1ed9c3
  resourceVersion: "1633"
  uid: 1c658959-11a4-4ec5-8532-e6e5dc9a8de7
spec: {}
