apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-10-08T05:59:33Z"
  generation: 1
  labels:
    app: myweb
  name: myweb
  namespace: myproject-sun
  uid: 12bc584d-95aa-4910-873f-0248ab338a3a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myweb
    spec:
      containers:
      - image: quay.io/redhattraining/versioned-hello:v1.0
        imagePullPolicy: IfNotPresent
        name: hello-world-nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
